module.exports = {
    MissingPasswordError : '密码没有输入',
    AttemptTooSoonError : '帐号被锁住，请一会再尝试',
    TooManyAttemptsError : '由于你多次登录失败，您的帐号暂时被锁',
    NoSaltValueStoredError : 'Authentication not possible. No salt value stored',
    IncorrectPasswordError : '密码输入错误',
    IncorrectOldPasswordError : '旧密码输入错误',
    PasswordSameError : '新密码不能与旧密码相同',
    IncorrectUsernameError : '您输入的用户不存在',
    MissingUsernameError : '用户名没有输入',
    MissingEmailError : '邮箱没有输入',
    UserExistsError : '您注册的用户名已经被注册',
    UserNotExistsError : '邮箱对应的用户不存在，请确认后再输入',
    EmailExistsError : '您注册的邮箱已经被使用',
    TempUserNotFoundError : '邮箱认证失败，您的认证地址可能已经过期',
    MissTagNameError: '版面名称没有填写',
    TagNameLenMoreError: '版面名称不能大于24个字符',
    TagNoJoinExitError: '取消订阅失败, 也许您在取消一个没有订阅过的版面...',
    TagRepeatJoinError: '订阅版面失败, 也许您已经订阅了该版面...',
};
